version: "3"
services:
  db:
    image: postgres:14.3
    environment:
      POSTGRES_DB: adverts
      POSTGRES_USER: pavel
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
    - ~/adverts/postgres_data

  server:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      DATABASE-URL: postgres://pavel:root@db:5432/adverts
    user: root
    links: 
      - db
