db_username: "pavel"
db_name: "adverts"
db_password: "root"
db_host: "db:5432"

server_addr: ":8080"
rw_timeout: 10
header_mbs: 2

jwt_sign: "asdASD@!#awAS12354EQW"

email: "test.adverts123@gmail.com"
password: "pUzWd4rUd7k8F5e"
smtp: "smtp.gmail.com"
smtp_port: ":587"

password_min: 8
password_max: 35

advert_body_min: 30
advert_body_max: 500
advert_title_min: 5
advert_title_max: 27
price_max: 1000000

redis_host : 6379
redis_password : ""
redis_db : 0