db_username: "pavel"
db_name: "adverts"
db_password: "root"
db_host: "db:5432"

server_addr: ":8080"
rw_timeout: 10
header_mbs: 2

jwt_sign: "asdASD@!#awAS12354EQW"

email: "test.adverts123@gmail.com"
password: "pUzWd4rUd7k8F5e"

password_min: 8
password_max: 35
advert_min: 30
advert_max: 500
price_max: 1000000
